export const cities = [
  { name: "البحيرة", iso: "Al Buḩayrah", displayName: "البحيرة" },
  { name: "القاهرة", iso: "Al Qāhirah", displayName: "القاهرة" },
  { name: "مطروح", iso: "Maţrūḩ", displayName: "مطروح" },
  {
    name: "البحر الأحمر",
    iso: "Al Baḩr al Aḩmar",
    displayName: "البحر الأحمر",
  },
  { name: "الإسكندرية", iso: "Al Iskandarīyah", displayName: "الإسكندرية" },
  { name: "الدقهلية", iso: "Ad Daqahlīyah", displayName: "الدقهلية" },
  { name: "الفيوم", iso: "Al Fayyūm", displayName: "الفيوم" },
  { name: "الغربية", iso: "Al Gharbīyah", displayName: "الغربية" },
  { name: "الإسماعيلية", iso: "Al Ismā'īlīyah", displayName: "الإسماعيلية" },
  { name: "الجيزة", iso: "Al Jīzah", displayName: "الجيزة" },
  { name: "المنُوفيّة", iso: "Al Minūfīyah", displayName: "المنُوفيّة" },
  { name: "المنيا", iso: "Al Minyā", displayName: "المنيا" },
  { name: "القليوبية", iso: "Al Qalyūbīyah", displayName: "القليوبية" },
  { name: "الأقصر", iso: "Al Uqşur", displayName: "الأقصر" },
  {
    name: "الوادي الجديد",
    iso: "Al Wādī al Jadīd",
    displayName: "الوادي الجديد",
  },
  { name: "السويس", iso: "As Suways", displayName: "السويس" },
  { name: "الشرقية", iso: "Ash Sharqīyah", displayName: "الشرقية" },
  { name: "أسوان", iso: "Aswān", displayName: "أسوان" },
  { name: "أسيوط", iso: "Asyūţ", displayName: "أسيوط" },
  { name: "بني سويف", iso: "Banī Suwayf", displayName: "بني سويف" },
  { name: "بورسعيد", iso: "Būr Saīd", displayName: "بورسعيد" },
  { name: "دمياط", iso: "Dumyāţ", displayName: "دمياط" },
  { name: "جنوب سيناء", iso: "Janūb Sīnā'", displayName: "جنوب سيناء" },
  { name: "كفر الشيخ", iso: "Kafr ash Shaykh", displayName: "كفر الشيخ" },
  { name: "قنا", iso: "Qinā", displayName: "قنا" },
  { name: "شمال سيناء", iso: "Shamāl Sīnā'", displayName: "شمال سيناء" },
  { name: "سوهاج", iso: "Sohaj", displayName: "سوهاج" },
];
